# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
