# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorja', '0002_auto_20161019_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='user',
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
