# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import oorja.models


class Migration(migrations.Migration):

    dependencies = [
        ('oorja', '0003_auto_20161020_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventFlex',
            field=models.ImageField(default='event_images/<built-in function id>.jpg', upload_to=oorja.models.content_file_name),
        ),
        migrations.AddField(
            model_name='events',
            name='eventRegDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
