# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oorja.models


class Migration(migrations.Migration):

    dependencies = [
        ('oorja', '0004_auto_20161020_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='event_images/<built-in function id>.jpg', upload_to=oorja.models.content_file_name)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oorja.Events')),
            ],
        ),
    ]
