# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorja', '0006_remove_events_eventflex'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
